### ISSUE TITLE
Add JavaScript support

### ISSUE THREAD

**Issue by derekchiang** [oraclize/encrypted-queries#3]
I'm implementing a dapp that runs entirely in the browser, which means that I don't have access to Python.

**Comment by D-Nice** [comment]
You'll require this then to create encrypted queries for users with Oraclize on the fly?

**Comment by derekchiang** [comment]
Yup!

**Comment by D-Nice** [comment]
We have an api endpoint that allows you to do the encryption.

Send a POST request to `https://api.oraclize.it/v1/utils/encryption/encrypt` and include what you want encrypted in the body, within message key. Example: 
```json
{
	"message": "\"I am a String, about to be encrypted\""
}
```

and here's an example of a successful response:
```
{
    "result": "BD0RlU8qlK+ybnW/Iis58uRxBv02tCPJMWSkpSKpXVQ0C8LHCVlqosWoZP/Q4xgbo/qO/M/Z0khGv6HKNEwcnZfkRPtEBH085eRXGxqSkFuXgAf4TEhh27r5yivBye1J10NU79AbLIpG5B6RWHfaxu/BE1uL/2E=",
    "success": true
}
```

You can also test whether an encrypted string will work by hitting the `https://api.oraclize.it/v1/utils/encryption/decrypt` POST endpoint where the body contains the encrypted string as the message, and it should return a success key.
