### ISSUE TITLE
fix: deprecation warnings

### ISSUE THREAD

**Issue by D-Nice** [oraclize/encrypted-queries#5]
User reported following warnings from the script:

`
CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
`

**Comment by D-Nice** [comment]
ping @danielglauser

**Comment by danielglauser** [comment]
@D-Nice Looks good, the warnings are gone on my end. Thanks!
